CREATE UNIQUE INDEX IF NOT EXISTS topics_default_name_key ON public.topics (name) WHERE teacher_id IS NULL;

INSERT INTO public.topics (teacher_id, name, is_default, sort_order)
SELECT NULL, v.name, true, v.ord
FROM (VALUES
('Planes',1),('Solids',2),('Cross-Sections of Three-Dimensional Objects',3),('Constructions',4),('Constructions (Advanced)',5),
('Points, Lines, and Planes',6),('Parallel and Perpendicular Lines',7),('Proofs: Lines and Angles',8),('Directed Line Segments',9),
('Triangle Proofs',10),('Triangle Congruence',11),('Triangle Similarity',12),('Triangle Similarity Proofs',13),('Special Right Triangles',14),
('Triangle Inequality Theorem',15),('Parallelogram Proofs',16),('Special Quadrilaterals',17),('Interior and Exterior Angles',18),
('Polygon Similarity',19),('Coordinate Geometry Proofs',20),('Equations of Circles',21),('Chords, Secants, and Tangents',22),('Inscribed Angles',23),
('Arc Length and Sector Area',24),('Inscribed and Circumscribed Circles',25),('Rotations',26),('Reflections',27),('Translations',28),('Dilations',29),
('Compositions of Transformations',30),('Symmetry',31),('Trigonometric Ratios',32),('Cofunctions',33),('Solving for a Side',34),
('Solving for an Angle',35),('Law of Sines',36),('Law of Cosines',37),('Definitions and Biconditionals',38),('Conditional Statements',39),
('Negations',40),('Proof Techniques',41),('Area of Polygons',42),('Area of Regular Polygons',43),('Area of Circles',44),
('Area of Composite Figures',45),('Volume of Prisms',46),('Volume of Cylinders',47),('Volume of Pyramids',48),('Volume of Cones',49),
('Volume of Spheres',50),('Surface Area of Prisms',51),('Surface Area of Cylinders',52),('Surface Area of Pyramids',53),('Surface Area of Cones',54),
('Surface Area of Spheres',55),('Cavalieri''s Principle',56),('Density',57),('Distance Formula',58),('Midpoint Formula',59),('Slope',60),
('Equations of Lines',61),('Equations of Parabolas',62),('Coordinate Proofs',63),('Partitioning a Line Segment',64),
('Perimeter in the Coordinate Plane',65),('Area in the Coordinate Plane',66),('Rigid Motions',67),('Rotational Symmetry',68),('Line Symmetry',69),
('Mapping a Figure onto Itself',70),('Congruent Triangles',71),('Triangle Congruence: SSS',72),('Triangle Congruence: SAS',73),
('Triangle Congruence: ASA',74),('Triangle Congruence: AAS',75),('Triangle Congruence: HL',76),('CPCTC',77),('Similar Triangles',78),
('Triangle Similarity: AA',79),('Triangle Similarity: SAS',80),('Triangle Similarity: SSS',81),('Proportions in Similar Triangles',82),
('Side Splitter Theorem',83),('Midsegment of a Triangle',84),('Similarity Transformations',85),('Scale Factor',86),('Polynomials',87),
('Factoring Polynomials',88),('Operations with Polynomials',89),('Solving Linear Equations',90),('Solving Linear Inequalities',91),
('Solving Quadratics by Factoring',92),('Solving Quadratics by Graphing',93),('Completing the Square',94),('Quadratic Formula',95),('Vertex Form',96),
('Function Notation',97),('Domain and Range',98),('Rate of Change',99),('Graphing Functions',100),('Transformations of Functions',101),
('Writing Linear Equations',102),('Graphing Linear Equations',103),('Solving Systems Graphically',104),('Solving Systems Algebraically',105),
('Systems of Inequalities',106),('Regression',107),('Correlation Coefficient',108),('Residuals',109),('Polynomial Identities',110),
('Zeros of Polynomials',111),('Remainder and Factor Theorems',112),('Polynomial Graphs',113),('Rational Expressions',114),('Rational Equations',115),
('Direct and Inverse Variation',116),('Radicals',117),('Radical Equations',118),('Complex Numbers',119),('Operations with Complex Numbers',120),
('Exponential Functions',121),('Exponential Equations',122),('Logarithmic Functions',123),('Properties of Logarithms',124),
('Exponential Growth and Decay',125),('Unit Circle',126),('Trigonometric Functions',127),('Graphing Trigonometric Functions',128),
('Trigonometric Identities',129),('Solving Trigonometric Equations',130),('Arithmetic Sequences',131),('Geometric Sequences',132),('Series',133),
('Probability',134),('Permutations and Combinations',135),('Normal Distribution',136),('Functions and Function Notation',137),('Inverse Functions',138),
('Composition of Functions',139),('Polynomial Functions',140),('Zeros of Polynomial Functions',141),('Rational Functions',142),('Asymptotes',143),
('Partial Fractions',144),('Exponential and Logarithmic Equations',145),('Radian and Degree Measure',146),('Graphs of Trigonometric Functions',147),
('Inverse Trigonometric Functions',148),('Sum and Difference Formulas',149),('Circles',150),('Parabolas',151),('Ellipses',152),('Hyperbolas',153),
('Vectors in the Plane',154),('Vector Operations',155),('Dot Product',156),('Parametric Equations',157),('Finding Limits Graphically',158),
('Finding Limits Algebraically',159),('Continuity',160),('Introduction to Derivatives',161),('Infinite Series',162),('Binomial Theorem',163),
('Central Idea and Theme',164),('Text Structure and Organization',165),('Author''s Purpose and Point of View',166),('Inference and Evidence',167),
('Vocabulary in Context',168),('Characterization',169),('Literary Devices',170),('Symbolism and Allegory',171),('Tone and Mood',172),
('Narrative Perspective',173),('Argumentative Writing',174),('Informative/Explanatory Writing',175),('Narrative Writing',176),('Research Skills',177),
('Evidence Integration',178),('Sentence Structure',179),('Usage and Conventions',180),('Punctuation',181),('Word Choice and Style',182),
('Colonial Period',183),('American Revolution',184),('Constitution and New Nation',185),('Civil War and Reconstruction',186),
('Industrialization and Progressivism',187),('World War I and the 1920s',188),('Great Depression and New Deal',189),('World War II',190),
('Cold War Era',191),('Civil Rights Movement',192),('Ancient Civilizations',193),('Classical Civilizations',194),('Post-Classical Era',195),
('Renaissance and Reformation',196),('Age of Exploration',197),('Age of Revolutions',198),('Imperialism',199),('World Wars',200),
('Cold War and Decolonization',201),('Constitutional Foundations',202),('Rights and Responsibilities',203),('Government Structure',204),
('Political Processes',205),('Physical Geography',206),('Human Geography',207),('Economic Systems',208),('Trade and Globalization',209),
('Cell Structure and Function',210),('Cell Organelles',211),('Cell Membrane and Transport',212),('Cellular Respiration',213),('Photosynthesis',214),
('Cell Division - Mitosis',215),('Cell Division - Meiosis',216),('DNA Structure and Replication',217),('Protein Synthesis',218),
('Mendelian Genetics',219),('Punnett Squares',220),('Genetic Variations',221),('Mutations',222),('Genetic Engineering',223),('Natural Selection',224),
('Evidence of Evolution',225),('Adaptation',226),('Speciation',227),('Evolutionary Relationships',228),('Ecosystems and Biomes',229),
('Food Chains and Webs',230),('Energy Flow',231),('Biogeochemical Cycles',232),('Population Dynamics',233),('Symbiotic Relationships',234),
('Human Impact on Environment',235),('Digestive System',236),('Circulatory System',237),('Respiratory System',238),('Nervous System',239),
('Immune System',240),('Reproductive System',241),('Homeostasis',242),('Microscope Use',243),('Scientific Method',244),('Data Analysis',245),
('Laboratory Safety',246),('Solar System',247),('Earth-Moon System',248),('Seasons and Tilt',249),('Phases of the Moon',250),('Eclipses',251),
('Stars and Galaxies',252),('Mineral Identification',253),('Rock Cycle',254),('Igneous Rocks',255),('Sedimentary Rocks',256),('Metamorphic Rocks',257),
('Continental Drift',258),('Plate Boundaries',259),('Earthquakes',260),('Volcanoes',261),('Mountain Building',262),('Weathering Types',263),
('Erosion and Deposition',264),('Soil Formation',265),('Glaciers',266),('Mass Movement',267),('Atmospheric Layers',268),('Weather Variables',269),
('Air Masses and Fronts',270),('Storms and Severe Weather',271),('Weather Maps',272),('Climate Zones',273),('Water Cycle',274),('Groundwater',275),
('Ocean Currents',276),('Tides',277),('Ocean Floor Features',278),('Geologic Time Scale',279),('Fossils and Index Fossils',280),('Relative Dating',281),
('Absolute Dating',282),('Mass Extinctions',283),('Reading Topographic Maps',284),('Using the ESRT',285),('Latitude and Longitude',286),
('Coordinate Systems',287),('Classification of Matter',288),('Physical and Chemical Properties',289),('States of Matter',290),('Phase Changes',291),
('Heat and Temperature',292),('Calorimetry',293),('Atomic Models',294),('Subatomic Particles',295),('Electron Configuration',296),
('Isotopes and Atomic Mass',297),('Nuclear Chemistry',298),('Radioactive Decay',299),('Half-Life',300),('Periodic Trends',301),
('Groups and Periods',302),('Metals, Nonmetals, and Metalloids',303),('Electronegativity',304),('Ionization Energy',305),('Atomic Radius',306),
('Ionic Bonding',307),('Covalent Bonding',308),('Metallic Bonding',309),('Lewis Dot Structures',310),('Molecular Geometry',311),('Polarity',312),
('Intermolecular Forces',313),('Naming Compounds',314),('Writing Chemical Formulas',315),('Balancing Chemical Equations',316),
('Types of Chemical Reactions',317),('Synthesis Reactions',318),('Decomposition Reactions',319),('Single and Double Replacement',320),
('Mole Concept',321),('Molar Mass',322),('Percent Composition',323),('Empirical and Molecular Formulas',324),('Mole-to-Mole Calculations',325),
('Mass-to-Mass Calculations',326),('Limiting Reagent',327),('Types of Solutions',328),('Concentration and Molarity',329),('Solubility Rules',330),
('Dilution',331),('Colligative Properties',332),('Properties of Acids and Bases',333),('pH Scale',334),('Neutralization Reactions',335),
('Titration',336),('Buffers',337),('Reaction Rate',338),('Factors Affecting Rate',339),('Activation Energy',340),('Chemical Equilibrium',341),
('Le Chatelier''s Principle',342),('Equilibrium Constants',343),('Oxidation States',344),('Redox Reactions',345),('Balancing Redox Equations',346),
('Electrochemical Cells',347),('Electrolysis',348),('Hydrocarbons',349),('Functional Groups',350),('Isomers',351),('Organic Reactions',352),
('Polymers',353),('Distance and Displacement',354),('Speed and Velocity',355),('Acceleration',356),('Motion Graphs',357),('Free Fall',358),
('Projectile Motion',359),('Kinematic Equations',360),('Newton''s First Law',361),('Newton''s Second Law',362),('Newton''s Third Law',363),
('Force Diagrams',364),('Friction',365),('Weight and Normal Force',366),('Inclined Planes',367),('Uniform Circular Motion',368),
('Centripetal Force',369),('Universal Gravitation',370),('Gravitational Fields',371),('Satellite Motion',372),('Momentum',373),('Impulse',374),
('Impulse-Momentum Theorem',375),('Conservation of Momentum',376),('Elastic Collisions',377),('Inelastic Collisions',378),('Work',379),
('Kinetic Energy',380),('Potential Energy',381),('Conservation of Energy',382),('Work-Energy Theorem',383),('Power',384),('Simple Machines',385),
('Electric Charge',386),('Coulomb''s Law',387),('Electric Fields',388),('Electric Potential',389),('Conductors and Insulators',390),
('Charging Methods',391),('Current and Voltage',392),('Resistance and Ohm''s Law',393),('Series Circuits',394),('Parallel Circuits',395),
('Combination Circuits',396),('Power in Circuits',397),('Circuit Analysis',398),('Magnetic Fields',399),('Magnetic Force on Charges',400),
('Magnetic Force on Current',401),('Electromagnetic Induction',402),('Motors and Generators',403),('Wave Properties',404),('Wave Types',405),
('Wave Equation',406),('Reflection',407),('Refraction',408),('Diffraction',409),('Interference',410),('Standing Waves',411),('Doppler Effect',412),
('Sound Waves',413),('Sound Speed',414),('Sound Intensity',415),('Resonance',416),('Beats',417),('Electromagnetic Spectrum',418),('Ray Diagrams',419),
('Plane Mirrors',420),('Curved Mirrors',421),('Snell''s Law',422),('Lenses',423),('Total Internal Reflection',424),('Photoelectric Effect',425),
('Wave-Particle Duality',426),('Energy Levels',427),('Photon Energy',428),('De Broglie Wavelength',429),('Special Relativity',430),
('Mass-Energy Equivalence',431),('Calculating Gross Pay',432),('Understanding Pay Stubs',433),('Net Pay vs Gross Pay',434),
('Overtime Pay Calculations',435),('Tips and Commission',436),('Part-Time Job Budgeting',437),('W-4 Form and Withholdings',438),
('Tax Brackets and Marginal Rates',439),('Filing Status (Single, MFJ, HOH)',440),('Standard vs Itemized Deductions',441),
('Calculating Taxable Income',442),('Federal Tax Calculations',443),('Effective vs Marginal Tax Rate',444),('W-2 Forms and Tax Returns',445),
('Tax Credits vs Deductions',446),('NYS Income Tax Brackets',447),('FICA Taxes (Social Security & Medicare)',448),('Self-Employment Tax',449),
('NYS and NYC Local Taxes',450),('What is Credit?',451),('Credit Reports and Bureaus',452),('Credit Score Components',453),
('Payment History Impact (35%)',454),('Credit Utilization (30%)',455),('Credit History Length (15%)',456),('Credit Mix (10%)',457),
('New Credit Inquiries (10%)',458),('Calculating Credit Utilization Ratio',459),('Late Payment Score Impact',460),('Ideal Utilization (Under 30%)',461),
('Score Recovery Strategies',462),('Credit Score Ranges (300-850)',463),('Debt-to-Credit Ratio Analysis',464),('Annual Percentage Rate (APR)',465),
('Minimum Payment Traps',466),('Interest Charge Calculations',467),('Credit Card Fees',468),('Secured vs Unsecured Cards',469),
('Building Credit Responsibly',470),('Rent Affordability (30% Rule)',471),('Security Deposits and First/Last Month',472),('Renter''s Insurance',473),
('Utility Budgeting',474),('Lease Agreement Terms',475),('Credit Score Requirements for Renting',476),('Move-In Cost Calculations',477),
('Creating a Monthly Budget',478),('50/30/20 Budget Rule',479),('Fixed vs Variable Expenses',480),('Emergency Fund Calculations',481),
('Opportunity Cost',482),('Tracking Spending',483),('Calculating Monthly Car Payments',484),('Loan vs Lease Comparison',485),
('Down Payment and Trade-In',486),('APR and Total Interest Paid',487),('Depreciation Calculations',488),('Car Insurance Requirements',489),
('Total Cost of Car Ownership',490),('MSRP and Residual Value',491),('Money Factor to APR Conversion',492),('Monthly Lease Payment Formula',493),
('Capitalized Cost and Fees',494),('Mileage Limits and Penalties',495),('Splitting Expenses with Roommates',496),('Joint vs Separate Accounts',497),
('Financial Communication in Relationships',498),('Co-signing Loans: Risks and Responsibilities',499),('Authorized User on Credit Cards',500),
('Wedding and Event Budgeting',501),('Simple vs Compound Interest',502),('Rule of 72',503),('High-Yield Savings Accounts',504),
('401(k) and Employer Match',505),('Roth IRA Contributions',506),('Time Value of Money',507),('Additional Costs: Fees',508),
('Additional Costs: Escrow',509),('Total Housing Payments',510),('Paying Off a Mortgage',511),('Home Ownership Wrap-Up',512),
('Car Insurance Premiums',513),('Suggested Premium',514),('Property and Renters Insurance',515),('Life Insurance',516),
('Calculating Life Insurance Premiums',517),('Retirement Accounts',518),('Insurance and Retirement Wrap-Up',519),('CDs (Certificates of Deposit)',520),
('Annuities',521),('Bonds',522),('Stocks',523),('The Stock Market',524),('Prediction',525),('Periodic Investment',526),
('Retirement and Periodic Investment',527),('Individual Net Worth',528),('Investments Wrap-Up',529),('Bond Fundamentals',530),
('Bond Face Value and Purchase Price',531),('Coupon Rate and Payment Calculations',532),('Annual vs Semiannual Coupon Payments',533),
('Total Bond Payments Over Time',534),('Bond Total Return on Investment',535),('Current Yield Calculations',536),('Yield to Maturity (YTM)',537),
('Premium vs Discount Bonds',538),('Government vs Corporate Bonds',539),('Bond Maturity and Interest Rate Risk',540),
('Municipal Bond Tax Advantages',541),('Comparing Bond Investments',542),('Zero-Coupon Bonds',543),('Cost and Revenue Functions',544),('Profit',545),
('Solving Systems of Equations',546),('Matrices',547),('Factors Affecting Business',548),('Maximizing Revenue or Minimizing Cost',549),
('Running a Business',550),('Storage, Inventory, and Other Business Concerns',551),('Business Wrap-Up',552),('GDP Calculation',553),
('GDP Growth Rate',554),('Nominal vs Real GDP',555),('Inflation and CPI',556),('Unemployment Rate',557),('FAFSA and Financial Aid',558),
('Federal vs Private Loans',559),('Loan Repayment Plans',560),('Interest Accrual While in School',561),('Total Cost of College',562),
('Scholarships and Grants',563),('Understanding Greetings & Introductions',564),('Following Classroom Instructions',565),
('Comprehending Weather Reports',566),('Understanding Phone Conversations',567),('Following News Broadcasts',568),('Listening to Song Lyrics',569),
('Reading Restaurant Menus',570),('Understanding Store Signs & Advertisements',571),('Reading Social Media Posts',572),
('Interpreting Job Listings',573),('Reading Apartment Rental Ads',574),('Understanding Product Labels',575),('Reading News Articles',576),
('Introducing Yourself',577),('Ordering Food at a Restaurant',578),('Asking for Directions',579),('Shopping Conversations',580),
('Job Interview Role Play',581),('Making Plans with Friends',582),('Discussing Current Events',583),('Negotiating & Problem Solving',584),
('Describing Your Family',585),('Presenting About Your School',586),('Describing Daily Routines',587),('Giving Oral Reports on Cultural Topics',588),
('Presenting Future Career Plans',589),('Debating Social Issues',590),('Writing Personal Introductions',591),('Completing Job Applications',592),
('Writing Emails to Friends',593),('Composing Cover Letters',594),('Writing Formal Complaints',595),('Creating Social Media Content',596),
('Writing Persuasive Essays',597),('Job Application Vocabulary',598),('Interview Questions & Responses',599),('Understanding Work Schedules',600),
('Workplace Communication',601),('Calling in Sick / Requesting Time Off',602),('Understanding Paystubs',603),('Apartment Hunting Vocabulary',604),
('Reading Lease Agreements',605),('Communicating with Landlords',606),('Reporting Maintenance Issues',607),('Setting Up Utilities',608),
('Roommate Agreements',609),('Making Friends & Small Talk',610),('Expressing Feelings & Emotions',611),('Planning Dates & Activities',612),
('Meeting Family Members',613),('Resolving Conflicts',614),('Cultural Dating Customs',615),('Traditional Holidays & Celebrations',616),
('Food & Cuisine Traditions',617),('Music & Dance',618),('Art & Literature',619),('Famous Figures & Historical Events',620),('Sports & Recreation',621),
('Family Structures & Values',622),('Education Systems',623),('Work-Life Balance',624),('Social Etiquette & Manners',625),('Attitudes Toward Time',626),
('Comparing Cultural Perspectives',627),('Present Tense Conjugations',628),('Past Tense Narration',629),('Future Tense Expressions',630),
('Question Formation',631),('Subjunctive Mood',632),('Conditional Expressions',633),('Object Pronouns',634),('Numbers, Dates & Time',635),
('Colors & Physical Descriptions',636),('Clothing & Fashion',637),('Food & Beverages',638),('Transportation',639),('Health & Body Parts',640),
('Technology & Social Media',641),('Purposes of Government',642),('Types of Government',643),('Constitutional Principles',644),('Federalism',645),
('Separation of Powers',646),('Checks and Balances',647),('Structure of Congress',648),('Powers of Congress',649),('How a Bill Becomes Law',650),
('Congressional Committees',651),('Representation and Redistricting',652),('Presidential Powers',653),('Executive Orders',654),
('The Cabinet and Federal Agencies',655),('Presidential Succession',656),('Electoral College',657),('Structure of Federal Courts',658),
('Supreme Court Powers',659),('Judicial Review',660),('Landmark Supreme Court Cases',661),('Rights of the Accused',662),('Bill of Rights',663),
('Civil Liberties',664),('Civil Rights',665),('Citizenship and Naturalization',666),('Civic Participation',667),('Political Parties',668),
('Elections and Voting',669),('Interest Groups and Lobbying',670),('Media and Public Opinion',671),('Campaign Finance',672),('Scarcity and Choice',673),
('Factors of Production',674),('Circular Flow Model',675),('Law of Demand',676),('Law of Supply',677),('Market Equilibrium',678),
('Price Elasticity',679),('Shifts in Supply and Demand',680),('Perfect Competition',681),('Monopoly',682),('Oligopoly',683),
('Monopolistic Competition',684),('Market Failures',685),('Gross Domestic Product (GDP)',686),('Inflation and Deflation',687),('Unemployment',688),
('Business Cycle',689),('Economic Indicators',690),('Functions of Money',691),('Federal Reserve System',692),('Monetary Policy',693),
('Interest Rates',694),('Banking System',695),('Fiscal Policy',696),('Taxation',697),('Government Spending',698),('National Debt',699),
('Trade Policy',700),('International Trade',701),('Comparative Advantage',702),('Exchange Rates',703),('Trade Barriers',704),('Globalization',705),
('Budgeting',706),('Saving and Investing',707),('Credit and Debt',708),('Insurance',709),('Consumer Rights',710)
) AS v(name, ord)
ON CONFLICT (name) WHERE teacher_id IS NULL DO NOTHING;